### ISSUE TITLE
Home page empty

### ISSUE THREAD

**Issue by SarahKit** [hidelab/genometranslationcommons#3]
Going to GTC from genometranslationcommons.org arrives at a blank page

**Comment by drj11** [comment]
Specifically, if you visit

http://genometranslationcommons.org/

you end up at an empty page.

with the URL https://beta.genometranslationcommons.org//#/

(note the double «//»)

**Comment by drj11** [comment]
Note: if you arrive via https or via beta.genometranslationcommons.org then you don't see this behaviour.
It's to do with the redirect from HTTP to HTTPS.

**Comment by drj11** [comment]
The redirect for the bare domain `genometranslationcommons.org` appears to be adding an extra `/` and this is confusing everything else.

**Comment by drj11** [comment]
The redirect from `genometranslationcommons.org` to `https://beta.genometranslationcommons.org/` is done by AWS S3 (there is a bucket called `genometranslationcommons.org`).
In order to work as required, the configuration of this bucket must avoid putting a `/` at the end of the domain.

I have fixed it by removing the erroneous trailing '/' from the configuration of this bucket.

**Comment by drj11** [comment]
Fixed.
